### ISSUE TITLE
Hints improvement

### ISSUE THREAD

**Issue by Miqueas** [bung87/vscode-nim-lsp#10]
Hi, first of all, thanks for this extension.

I'm opening this issue because I think these hints needs an improvement:

![image](https://github.com/bung87/vscode-nim-lsp/assets/31262466/0685aa37-d67a-4eb1-a791-e4fb0877f553)

The documentation text inside there should be treated as Markdown and not be colored like that.

**Comment by bung87** [comment]
yeah, I knew that, it need to be handled in https://github.com/PMunch/nimlsp, I have made improvements into nimskull https://github.com/nim-works/nimskull/pull/879, gonna get chance port to nimlsp as well.

**Comment by Miqueas** [comment]
> yeah, I knew that, it need to be handled in https://github.com/PMunch/nimlsp, I have made improvements into nimskull [nim-works/nimskull#879](https://github.com/nim-works/nimskull/pull/879), gonna get chance port to nimlsp as well.

Oh I see, is in progress then, nice! Well, since looks like isn't a fault of the extension, I'm gonna close this then. Thanks for answering!
