### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by arkanoid87** [bung87/vscode-nim-lsp#3]
nimlsp 3.2 is in path, but extension fails with message

```
Connection to server got closed. Server will restart.
Connection to server got closed. Server will not be restarted.
```

nim 1.6

**Comment by bung87** [comment]
Do you use my fork version nimlsp https://github.com/bung87/nimlsp ?  
It's async version language server.

**Comment by arkanoid87** [comment]
nope, I used the @PMunch version. Why a fork for vscode?

**Comment by bung87** [comment]
Pmunch 's is sync version server , that's not preffer way.

**Comment by arkanoid87** [comment]
your extension is the only nimlsp extension available for vscode, you also submitted a PR suggesting your extension for @PMunch project. Considering that lsp should be the way to go for this kind of service and vscode is the most used ide for nim according to stats, could be worth merging the two and make it official?

**Comment by bung87** [comment]
I dont know if that could be merged into PMunch's or not.

**Comment by PMunch** [comment]
If it's just a fork I don't see why not. Unless you forked it a long time ago and it has drifted severely since then. I don't much care for you way of [documenting your commits though](https://github.com/bung87/nimlsp/commits/devel) so we'd need to clean up the history a bit if we merge them.

**Comment by bung87** [comment]
since nimlsp 0.4.6 become async server and this plugin also updated using channel communicate with server, guess this get fixed.
